sudo: required 
language: node_js
node_js:
    - 16
    
services: 
    - docker
before_install: 
    - docker build -t shangchewang/sample-app -f Dockerfile.dev .
script:     
    - docker run -e CI=true shangchewang/sample-app npm run test -- --coverage --watchAll=false
